### ISSUE TITLE
wayland + fcitx5 + alacritty

### ISSUE THREAD

**Issue by joelkoen** [fosskers/fosskers.ca#66]
Hi, I've just setup fcitx5 on my system and have noticed that the only app that I can't get to work with it is Alacritty. I've been doing some research in order to debug this, and came across [your arch linux setup post](https://www.fosskers.ca/en/blog/wayland). In it, under the Japanese Input section you mention:

> For now, here is a setup that works through dbus allowing us to change Methods and type Japanese in all Wayland and XWayland windows **except Alacritty**

I'm opening this issue to see if you've got fcitx working with Alacritty under wayland? If not, I'll close this issue and open a new issue in Alacritty's repo. Thanks!

**Comment by joelkoen** [comment]
I was also wondering if you found another terminal emulator that works if you don't use alacritty anymore, as that blog post is two years old now.

**Comment by fosskers** [comment]
Hi, thanks for the report! Yes I've been usind https://codeberg.org/dnkl/foot for some time, which specifically bills itself as a Wayland terminal.

**Comment by joelkoen** [comment]
Hmm, foot doesn't seem to work either, which is odd because it says it has IME support. I must be missing something on my system. Thanks for the fast response though!

**Comment by fosskers** [comment]
I'm definitely able to type Japanese into `foot`, so keep trying! It should be possible :+1:
